/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package task3;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  @Test
  void testSmallMatrix() {
    App classUnderTest = new App();
    assertEquals(
        classUnderTest.isKinMaxInColums(4, 3, 2, new int[] { 1, 2, 3, 4, 5, 6 }),
        true);
    assertEquals(
        classUnderTest.isKinMaxInColums(1, 3, 2, new int[] { 1, 2, 3, 4, 5, 6 }),
        false);
  }

  @Test
  void testOneEntryInMatrix() {
    App classUnderTest = new App();
    assertEquals(
        classUnderTest.isKinMaxInColums(10, 1, 1, new int[] { 10 }),
        true);
  }

  @Test
  void testBigMatrix() {
    App classUnderTest = new App();
    int[] matrix = new int[1000];
    int width = 20;
    int height = 1000 / width;

    for (int i = 0; i < matrix.length; i++) {
      matrix[i] = i;
    }

    assertEquals(
        classUnderTest.isKinMaxInColums(10, width, height, matrix),
        false);
    assertEquals(
        classUnderTest.isKinMaxInColums(999, width, height, matrix),
        true);
  }
}
