/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package task5;

import java.math.BigDecimal;

public class App {

  public static void main(String[] args) {
    Gold yellowGold = new Gold("United States", GoldColor.yellow, 10, new BigDecimal(24.91));
    System.out.println(yellowGold);
  }
}
