/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package task4;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;

class AppTest {
  @Test
  void testTransformSmallMatrix() {
    App classUnderTest = new App();
    int[] matrix = new int[] { 1, 2, 3, 4, 5, 6 };
    classUnderTest.transformMatrix(3, 2, matrix);
    assertTrue(Arrays.equals(
        matrix,
        new int[] { 3, 2, 1, 6, 5, 4 }));
  }

  @Test
  void testEqualElements() {
    App classUnderTest = new App();
    int[] matrix = new int[] { 2, 2, 3, 4, 5, 6 };
    classUnderTest.transformMatrix(3, 2, matrix);
    assertTrue(Arrays.equals(
        matrix,
        new int[] { 3, 2, 2, 6, 5, 4 }));
  }

  @Test
  void testTwoElementMatrix() {
    App classUnderTest = new App();
    int[] matrix = new int[] { 6, 5 };
    classUnderTest.transformMatrix(2, 1, matrix);
    assertTrue(Arrays.equals(
        matrix,
        new int[] { 5, 6 }));
  }

  @Test
  void testTwoEqualElementMatrix() {
    App classUnderTest = new App();
    int[] matrix = new int[] { 5, 5 };
    classUnderTest.transformMatrix(2, 1, matrix);
    assertTrue(Arrays.equals(
        matrix,
        new int[] { 5, 5 }));
  }

  @Test
  void testOneColumnMatrix() {
    App classUnderTest = new App();
    int[] matrix = new int[] { 5, 6 };
    classUnderTest.transformMatrix(1, 2, matrix);
    assertTrue(Arrays.equals(
        matrix,
        new int[] { 5, 6 }));
  }
}
